=== CuentaEducaSantiago/daw106.ieslossauces.es/106DAWProyectoDAW/106LMSGIProyectoLMSGI/ud4/03/03.dtd
<!ELEMENT programmingLanguages (lenguaje)+>
<!ELEMENT lenguaje (description, example)>
<!ATTLIST lenguaje lenguaje_name CDATA #IMPLIED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ATTLIST programmingLanguages
xmlns:xsi CDATA #IMPLIED
xsi:noNamespaceSchemaLocation CDATA #REQUIRED>

=== CuentaEducaSantiago/daw106.ieslossauces.es/106DAWProyectoDAW/106LMSGIProyectoLMSGI/ud4/03/03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE programmingLanguages SYSTEM "03.dtd">
<?xml-stylesheet href="estilos.css" type="text/css"?>
<programmingLanguages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="03.xsd">
    <lenguaje lenguaje_name="Python">
        <description><![CDATA[Python es un lenguaje de programación interpretado, de alto nivel y de propósito general.]]></description>
        <example><![CDATA[def saludo():
       print("¡Hola, Mundo!")
   
   saludo()]]></example>
    </lenguaje>
    <lenguaje lenguaje_name="JavaScript">
        <description><![CDATA[JavaScript es un lenguaje de programación que se utiliza para crear contenido dinámico en la web.]]></description>
        <example><![CDATA[function saludo() {
       alert("¡Hola, Mundo!");
   }

   saludo();]]></example>
    </lenguaje>
    <lenguaje lenguaje_name="Java">
        <description><![CDATA[Java es un lenguaje de programación de propósito general que es ampliamente utilizado en aplicaciones empresariales y móviles.]]></description>
        <example><![CDATA[public class Saludo {
       public static void main(String[] args) {
           System.out.println("¡Hola, Mundo!");
       }
   }]]></example>
    </lenguaje>
    <lenguaje lenguaje_name="C++">
        <description><![CDATA[C++ es un lenguaje de programación de propósito general, conocido por su eficiencia y uso en aplicaciones de alto rendimiento.]]></description>
        <example><![CDATA[#include <iostream>
   using namespace std;

   int main() {
       cout << "¡Hola, Mundo!" << endl;
       return 0;
   }]]></example>
    </lenguaje>
    <lenguaje lenguaje_name="Ruby">
        <description><![CDATA[Ruby es un lenguaje de programación dinámico y de alto nivel, conocido por su sintaxis simple y elegante.]]></description>
        <example><![CDATA[def saludo
     puts "¡Hola, Mundo!"
   end

   saludo]]></example>
    </lenguaje>
</programmingLanguages>
